include: package:flutter_lints/flutter.yaml  # ou package:lint/lint.yaml

linter:
  rules:
    prefer_final_locals: true
    avoid_print: true
    prefer_const_constructors: true
    require_trailing_commas: true