name: flex_ui
description: "Beautifully crafted commerce widgets to copy and paste into your storefront app."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  cached_network_image: ^3.4.1
  flutter:
    sdk: flutter
  shimmer: ^3.0.0
  widgetbook: ^3.9.0
  widgetbook_annotation: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  widgetbook_generator: ^3.9.0
  build_runner: ^2.4.12

flutter:
  uses-material-design: true
