name: flex_ui
description: Beautifully crafted commerce widgets to copy and paste into your storefront app.
publish_to: 'none'
version: 1.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  alchemist: ^0.11.0
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  file: ^7.0.1
  flutter:
    sdk: flutter
  flutter_localizations:
      sdk: flutter
  intl:  ^0.19.0
  provider: ^6.1.2
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.0+3
  widgetbook: ^3.10.1
  widgetbook_annotation: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  widgetbook_generator: ^3.9.0
  build_runner: ^2.4.12

flutter:
  uses-material-design: true
