name: Build and Upload Android App to BrowserStack

on:
  push:
    tags:
      - 'qa*'

permissions:
  contents: read

jobs:
  build-and-upload:
    name: Build and Upload Android App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Rename example.env to .env
        run: |
          if [ -f app/example.env ]; then
            mv app/example.env app/.env
            echo "Renamed app/example.env to app/.env"
          else
            echo "app/example.env not found"
          fi

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.0'

      - name: Install Dependencies
        run: |
          cd app
          flutter pub get

      - name: Build Android APK
        run: |
          cd app
          flutter build apk -t lib/main_development.dart --flavor development --release

      - name: Upload APK to BrowserStack
        env:
          BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
        run: |
          curl -u "$BROWSERSTACK_USERNAME:$BROWSERSTACK_ACCESS_KEY" \
            -X POST "https://api-cloud.browserstack.com/app-automate/upload" \
            -F "file=@app/build/app/outputs/flutter-apk/app-development-release.apk" \
            | jq '.'
